### ISSUE TITLE
nonmem2mrgsolve::nonmem2mrgsolve does not recognize .mod extension

### ISSUE THREAD

**Issue by stevechoy** [Andy00000000000/nonmem2mrgsolve#32]
Hi Andrew,

Nice work - just want to point that the function nonmem2mrgsolve::nonmem2mrgsolve assumes the model file ends in .ctl extension. Very commonly the model extension is instead .mod, which is not recognized for now.

**Comment by Andy00000000000** [comment]
Hi Steve,

Thanks for the feedback! I'll get that built in, hopefully within the next 2 weeks.

**Comment by Andy00000000000** [comment]
This is implemented now. Please let me know if you have any issues with it.
